#!/bin/bash
#
# Title:           Docker Uploader
# Author:          MrDoob
# Dockerowner:     MrDoob
# GNU:             General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'uploader'
        intport: '8080'
        extport: '7777'
        image: 'hawkinzzz/uploader:latest'

    - name: 'Remove uploader Container'
      docker_container:
        name: 'uploader'
        state: 'absent'

    # CORE (MANDATORY) ############################################################
    - name: 'Including main job'
      include_tasks: '/opt/coreapps/apps/_core.yml'
    - name: 'Including cleaner job'
      include_tasks: './cleaner.yml'
    - name: 'Including key and rclone job'
      include_tasks: './key.yml'
    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.redirect.entryPoint: 'https'

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/:/config:rw'
          - 'unionfs:/mnt'

    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

     ########## DEPLOYMENT ##########
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        hostname: 'uploader'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        capabilities:
          - 'SYS_ADMIN'
        privileged: true
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
        dns_servers:
          - '8.8.8.8'
          - '8.8.4.4'
